ALTER TABLE "market"."business_directories" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('simple', market.normalize_arabic(coalesce("market"."business_directories"."name_ar", ''))), 'A') || setweight(to_tsvector('simple', coalesce("market"."business_directories"."name_en", '')), 'A') || setweight(to_tsvector('simple', market.normalize_arabic(coalesce("market"."business_directories"."description_ar", ''))), 'B') || setweight(to_tsvector('simple', coalesce("market"."business_directories"."description", '')), 'B') || setweight(to_tsvector('simple', coalesce("market"."business_directories"."district", '')), 'C') || setweight(to_tsvector('simple', coalesce("market"."business_directories"."category", '')), 'C')) STORED;--> statement-breakpoint
ALTER TABLE "market"."investment_opportunities" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('simple', market.normalize_arabic(coalesce("market"."investment_opportunities"."title_ar", ''))), 'A') || setweight(to_tsvector('simple', coalesce("market"."investment_opportunities"."title_en", '')), 'A') || setweight(to_tsvector('simple', market.normalize_arabic(coalesce("market"."investment_opportunities"."description", ''))), 'B') || setweight(to_tsvector('simple', coalesce("market"."investment_opportunities"."area", '')), 'C')) STORED;--> statement-breakpoint
ALTER TABLE "market"."listings" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('simple', market.normalize_arabic(coalesce("market"."listings"."title_ar", ''))), 'A') || setweight(to_tsvector('simple', coalesce("market"."listings"."title_en", '')), 'A') || setweight(to_tsvector('simple', market.normalize_arabic(coalesce("market"."listings"."description", ''))), 'B') || setweight(to_tsvector('simple', coalesce("market"."listings"."address", '')), 'C') || setweight(to_tsvector('simple', coalesce("market"."listings"."district", '')), 'C') || setweight(to_tsvector('simple', coalesce("market"."listings"."sub_category", '')), 'C')) STORED;--> statement-breakpoint
CREATE INDEX "idx_biz_dir_search_vector" ON "market"."business_directories" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "idx_biz_dir_name_ar_trgm" ON "market"."business_directories" USING gin ("name_ar" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "idx_biz_dir_name_en_trgm" ON "market"."business_directories" USING gin ("name_en" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "idx_opportunities_search_vector" ON "market"."investment_opportunities" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "idx_opportunities_title_ar_trgm" ON "market"."investment_opportunities" USING gin ("title_ar" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "idx_opportunities_title_en_trgm" ON "market"."investment_opportunities" USING gin ("title_en" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "idx_listings_search_vector" ON "market"."listings" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "idx_listings_title_ar_trgm" ON "market"."listings" USING gin ("title_ar" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "idx_listings_title_en_trgm" ON "market"."listings" USING gin ("title_en" gin_trgm_ops);