import { USER } from '../../../../../scripts/seed/shared-ids.js';

/** User seed record (password hash is set at insert time) */
export interface SeedUser {
  id: string;
  email: string;
  phone: string | null;
  fullName: string;
  displayName: string | null;
  role: 'admin' | 'tourist' | 'resident' | 'student' | 'merchant' | 'driver' | 'guide' | 'investor';
  status: 'active';
  language: string;
  verifiedAt: Date | null;
}

const now = new Date();

/** Essential layer: 4 admins + 7 demo role users */
export const essentialUsers: SeedUser[] = [
  // ── Admins (team members) ──
  {
    id: USER.ADMIN_SAYED,
    email: 'sayed@hena-wadeena.online',
    phone: null,
    fullName: 'سيد',
    displayName: 'سيد',
    role: 'admin',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.ADMIN_KAREEM,
    email: 'kareem@hena-wadeena.online',
    phone: null,
    fullName: 'كريم',
    displayName: 'كريم',
    role: 'admin',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.ADMIN_TAHER,
    email: 'taher@hena-wadeena.online',
    phone: null,
    fullName: 'طاهر',
    displayName: 'طاهر',
    role: 'admin',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.ADMIN_SHAWQI,
    email: 'shawqi@hena-wadeena.online',
    phone: null,
    fullName: 'شوقي',
    displayName: 'شوقي',
    role: 'admin',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  // ── Demo role users ──
  {
    id: USER.TOURIST_SALMA,
    email: 'tourist@hena-wadeena.online',
    phone: '+201000000001',
    fullName: 'سلمى الزائرة',
    displayName: 'سلمى',
    role: 'tourist',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.RESIDENT_MOHAMED,
    email: 'resident@hena-wadeena.online',
    phone: '+201000000002',
    fullName: 'محمد الواحاتي',
    displayName: 'محمد',
    role: 'resident',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.STUDENT_NOUR,
    email: 'student@hena-wadeena.online',
    phone: '+201000000003',
    fullName: 'نور الطالبة',
    displayName: 'نور',
    role: 'student',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.MERCHANT_KHALED,
    email: 'merchant@hena-wadeena.online',
    phone: '+201000000004',
    fullName: 'خالد التاجر',
    displayName: 'خالد',
    role: 'merchant',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.DRIVER_AMRO,
    email: 'driver@hena-wadeena.online',
    phone: '+201000000005',
    fullName: 'عمرو السائق',
    displayName: 'عمرو',
    role: 'driver',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.GUIDE_YOUSSEF,
    email: 'guide@hena-wadeena.online',
    phone: '+201000000006',
    fullName: 'يوسف الدليل',
    displayName: 'يوسف',
    role: 'guide',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.INVESTOR_MAHMOUD,
    email: 'investor@hena-wadeena.online',
    phone: '+201000000007',
    fullName: 'محمود المستثمر',
    displayName: 'محمود المستثمر',
    role: 'investor',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
];

/** Showcase layer: additional users for a populated feel */
export const showcaseUsers: SeedUser[] = [
  {
    id: USER.GUIDE_FATMA,
    email: 'fatma.guide@hena-wadeena.online',
    phone: '+201000000008',
    fullName: 'فاطمة الصحراوية',
    displayName: 'فاطمة',
    role: 'guide',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.GUIDE_AHMED,
    email: 'ahmed.guide@hena-wadeena.online',
    phone: '+201000000009',
    fullName: 'أحمد المغامر',
    displayName: 'أحمد',
    role: 'guide',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.GUIDE_MARIAM,
    email: 'mariam.guide@hena-wadeena.online',
    phone: '+201000000010',
    fullName: 'مريم العلاجية',
    displayName: 'مريم',
    role: 'guide',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.GUIDE_OMAR,
    email: 'omar.guide@hena-wadeena.online',
    phone: '+201000000011',
    fullName: 'عمر المصور',
    displayName: 'عمر',
    role: 'guide',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.TOURIST_HASSAN,
    email: 'hassan@hena-wadeena.online',
    phone: '+201000000012',
    fullName: 'حسن الرحالة',
    displayName: 'حسن',
    role: 'tourist',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.TOURIST_LAYLA,
    email: 'layla@hena-wadeena.online',
    phone: '+201000000013',
    fullName: 'ليلى السائحة',
    displayName: 'ليلى',
    role: 'tourist',
    status: 'active',
    language: 'en',
    verifiedAt: now,
  },
  {
    id: USER.TOURIST_KARIM,
    email: 'karim@hena-wadeena.online',
    phone: '+201000000014',
    fullName: 'كريم الباحث',
    displayName: 'كريم',
    role: 'tourist',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
  {
    id: USER.STUDENT_SARA,
    email: 'sara.student@hena-wadeena.online',
    phone: '+201000000015',
    fullName: 'سارة الجامعية',
    displayName: 'سارة',
    role: 'student',
    status: 'active',
    language: 'ar',
    verifiedAt: now,
  },
];
