const SEED_USER_ID = '00000000-0000-4000-8000-000000000001';
const SEED_ADMIN_ID = '00000000-0000-4000-8000-000000000002';

export const seedIncidents = [
  {
    id: '01950000-0000-7000-8000-000000000101',
    reporterId: SEED_USER_ID,
    incidentType: 'litter' as const,
    status: 'reported' as const,
    descriptionAr: 'زجاجات بلاستيكية وأغلفة طعام متناثرة حول موقع التصوير الشهير',
    descriptionEn: 'Plastic bottles and food wrappers scattered around popular photo spot',
    lat: 27.3,
    lon: 28.0833,
    photos: ['/images/seed/incidents/incident-litter.jpg'] as string[],
    eeaaReference: null as string | null,
    adminNotes: null as string | null,
    resolvedBy: null as string | null,
  },
  {
    id: '01950000-0000-7000-8000-000000000102',
    reporterId: SEED_USER_ID,
    incidentType: 'fire_remains' as const,
    status: 'under_review' as const,
    descriptionAr: 'بقايا نار مخيم مع صخور متفحمة في موقع تخييم غير رسمي',
    descriptionEn: 'Campfire remnants with charred rocks at informal camping spot',
    lat: 27.25,
    lon: 28.15,
    photos: ['/images/seed/incidents/incident-fire-remains.jpg'] as string[],
    eeaaReference: null,
    adminNotes: null,
    resolvedBy: null,
  },
  {
    id: '01950000-0000-7000-8000-000000000103',
    reporterId: SEED_USER_ID,
    incidentType: 'vehicle_damage' as const,
    status: 'resolved' as const,
    descriptionAr: 'آثار مركبات على الطرق الوعرة عبر التكوينات الطباشيرية',
    descriptionEn: 'Off-road vehicle tracks through chalk formations',
    lat: 27.35,
    lon: 28.05,
    photos: ['/images/seed/incidents/incident-vehicle-damage.jpg'] as string[],
    eeaaReference: 'EEAA-2026-WD-0042',
    adminNotes: null,
    resolvedBy: SEED_ADMIN_ID,
  },
  {
    id: '01950000-0000-7000-8000-000000000104',
    reporterId: SEED_USER_ID,
    incidentType: 'illegal_dumping' as const,
    status: 'reported' as const,
    descriptionAr: 'نفايات بناء ملقاة بالقرب من طريق الوصول',
    descriptionEn: 'Construction waste dumped near access road',
    lat: 27.2,
    lon: 28.2,
    photos: ['/images/seed/incidents/incident-illegal-dumping.jpg'] as string[],
    eeaaReference: null,
    adminNotes: null,
    resolvedBy: null,
  },
  {
    id: '01950000-0000-7000-8000-000000000105',
    reporterId: SEED_USER_ID,
    incidentType: 'vandalism' as const,
    status: 'dismissed' as const,
    descriptionAr: 'بلاغ عن كتابات - تم التأكد أنها أنماط تآكل طبيعية',
    descriptionEn: 'Reported graffiti - confirmed natural erosion pattern',
    lat: 27.4,
    lon: 28.1,
    photos: [] as string[],
    eeaaReference: null,
    adminNotes: 'Inspected on-site. Natural chalk erosion mistaken for vandalism.',
    resolvedBy: SEED_ADMIN_ID,
  },
  {
    id: '01950000-0000-7000-8000-000000000106',
    reporterId: SEED_USER_ID,
    incidentType: 'litter' as const,
    status: 'under_review' as const,
    descriptionAr: 'كمية كبيرة من الأكياس البلاستيكية عالقة في التكوينات الصخرية',
    descriptionEn: 'Large amount of plastic bags caught in rock formations',
    lat: 27.28,
    lon: 28.12,
    photos: [] as string[],
    eeaaReference: null,
    adminNotes: null,
    resolvedBy: null,
  },
  {
    id: '01950000-0000-7000-8000-000000000107',
    reporterId: SEED_USER_ID,
    incidentType: 'fire_remains' as const,
    status: 'reported' as const,
    descriptionAr: 'حفرة نار حديثة مع قمامة محترقة جزئياً',
    descriptionEn: 'Recent fire pit with partially burned trash',
    lat: 27.32,
    lon: 28.07,
    photos: ['/images/seed/incidents/incident-fire-remains.jpg'] as string[],
    eeaaReference: null,
    adminNotes: null,
    resolvedBy: null,
  },
  {
    id: '01950000-0000-7000-8000-000000000108',
    reporterId: SEED_USER_ID,
    incidentType: 'vehicle_damage' as const,
    status: 'reported' as const,
    descriptionAr: 'آثار إطارات جديدة في منطقة صخور الفطر المحمية',
    descriptionEn: 'Fresh tire tracks in protected mushroom rock area',
    lat: 27.26,
    lon: 28.18,
    photos: [] as string[],
    eeaaReference: null,
    adminNotes: null,
    resolvedBy: null,
  },
];
