import { POI, USER } from '../../../../../scripts/seed/shared-ids.js';

export interface SeedPoi {
  id: string;
  nameAr: string;
  nameEn: string;
  description: string;
  category:
    | 'historical'
    | 'natural'
    | 'religious'
    | 'recreational'
    | 'accommodation'
    | 'restaurant'
    | 'service'
    | 'government'
    | 'solar_installation';
  address: string;
  phone?: string;
  lat: number;
  lon: number;
  submittedBy: string;
  approvedBy?: string; // Optional for pending POIs
  images?: string[];
  metadata?: Record<string, unknown>;
}

/** Pending POIs: user-submitted, awaiting admin review */
export const pendingPois: SeedPoi[] = [
  {
    id: POI.POI_PENDING_01,
    nameAr: 'مطعم الواحة الخضراء',
    nameEn: 'Green Oasis Restaurant',
    description: 'مطعم شعبي يقدم أشهى المأكولات المحلية والمشويات الطازجة في جو تقليدي',
    category: 'restaurant',
    address: 'شارع السوق، الخارجة',
    phone: '+20924925555',
    lat: 25.438,
    lon: 30.546,
    submittedBy: USER.RESIDENT_MOHAMED,
  },
  {
    id: POI.POI_PENDING_02,
    nameAr: 'عين بئر الجبل',
    nameEn: 'Mountain Well Spring',
    description: 'عين مياه طبيعية ساخنة محاطة بأشجار النخيل، مكان رائع للاسترخاء',
    category: 'natural',
    address: 'طريق الفرافرة - باويطي',
    lat: 27.12,
    lon: 27.85,
    submittedBy: USER.GUIDE_YOUSSEF,
  },
  {
    id: POI.POI_PENDING_03,
    nameAr: 'مسجد الشيخ عبد الرحيم',
    nameEn: 'Sheikh Abdel Rahim Mosque',
    description: 'مسجد تاريخي يعود تاريخه لأكثر من 200 عام، يتميز بطراز معماري فريد',
    category: 'religious',
    address: 'حي القديم، موط، الداخلة',
    lat: 25.492,
    lon: 28.974,
    submittedBy: USER.RESIDENT_MOHAMED,
  },
  {
    id: POI.POI_PENDING_04,
    nameAr: 'استراحة القمر الفضي',
    nameEn: 'Silver Moon Lodge',
    description: 'استراحة سياحية توفر غرف مريحة وإطلالة على الصحراء البيضاء',
    category: 'accommodation',
    address: 'طريق الصحراء البيضاء، الفرافرة',
    phone: '+20927512345',
    lat: 27.15,
    lon: 27.95,
    submittedBy: USER.MERCHANT_KHALED,
  },
  {
    id: POI.POI_PENDING_05,
    nameAr: 'ملعب الخارجة الرياضي',
    nameEn: 'Kharga Sports Stadium',
    description: 'الملعب الرئيسي لمدينة الخارجة يستضيف المباريات والفعاليات الرياضية',
    category: 'recreational',
    address: 'حي الملعب، الخارجة',
    lat: 25.442,
    lon: 30.558,
    submittedBy: USER.STUDENT_NOUR,
  },
];

// Inline IDs for showcase POIs 11–20
const P11 = 'aa110000-0000-4000-8000-000000000011';
const P12 = 'aa120000-0000-4000-8000-000000000012';
const P13 = 'aa130000-0000-4000-8000-000000000013';
const P14 = 'aa140000-0000-4000-8000-000000000014';
const P15 = 'aa150000-0000-4000-8000-000000000015';
const P16 = 'aa160000-0000-4000-8000-000000000016';
const P17 = 'aa170000-0000-4000-8000-000000000017';
const P18 = 'aa180000-0000-4000-8000-000000000018';
const P19 = 'aa190000-0000-4000-8000-000000000019';
const P20 = 'aa200000-0000-4000-8000-000000000020';

/** Essential layer: 5 POIs — one key location per city */
export const essentialPois: SeedPoi[] = [
  {
    id: POI.POI01,
    nameAr: 'مستشفى الخارجة العام',
    nameEn: 'Kharga General Hospital',
    description: 'المستشفى الرئيسي في مدينة الخارجة عاصمة محافظة الوادي الجديد',
    category: 'service',
    address: 'شارع جمال عبد الناصر، الخارجة',
    phone: '+20924921234',
    lat: 25.44,
    lon: 30.55,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/umfgtmwR__Y.jpg'],
  },
  {
    id: POI.POI02,
    nameAr: 'جامعة الوادي الجديد',
    nameEn: 'New Valley University',
    description: 'الجامعة الحكومية الرئيسية في محافظة الوادي الجديد',
    category: 'service',
    address: 'طريق الخارجة - أسيوط، الخارجة',
    lat: 25.45,
    lon: 30.56,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/a8ZSKCBE1xk.jpg'],
  },
  {
    id: POI.POI03,
    nameAr: 'مستشفى موط العام',
    nameEn: 'Mut General Hospital',
    description: 'المستشفى الرئيسي في مدينة موط بواحة الداخلة',
    category: 'service',
    address: 'شارع المستشفى، موط، الداخلة',
    phone: '+20926821234',
    lat: 25.4946,
    lon: 28.9781,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/GTigSDuTiN4.jpg'],
  },
  {
    id: POI.POI04,
    nameAr: 'مجلس مدينة الفرافرة',
    nameEn: 'Farafra City Council',
    description: 'مقر مجلس مدينة الفرافرة والخدمات الحكومية',
    category: 'government',
    address: 'وسط مدينة الفرافرة',
    phone: '+20927510123',
    lat: 27.0567,
    lon: 27.9703,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/AFuVCldRhjs.jpg'],
  },
  {
    id: POI.POI05,
    nameAr: 'مستشفى باريس المركزي',
    nameEn: 'Baris Central Hospital',
    description: 'المستشفى المركزي في مدينة باريس جنوب واحة الخارجة',
    category: 'service',
    address: 'وسط مدينة باريس',
    phone: '+20924991234',
    lat: 24.6544,
    lon: 30.5956,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/wiki-baris-1.jpg'],
  },
];

/** Showcase layer: additional POIs across all cities */
export const showcasePois: SeedPoi[] = [
  {
    id: POI.POI06,
    nameAr: 'ديوان عام محافظة الوادي الجديد',
    nameEn: 'New Valley Governorate Headquarters',
    description: 'المقر الرسمي لمحافظة الوادي الجديد وإدارة المحافظة',
    category: 'government',
    address: 'شارع الجمهورية، الخارجة',
    phone: '+20924920000',
    lat: 25.441,
    lon: 30.549,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/Rk8yY0UfPx0.jpg'],
  },
  {
    id: POI.POI07,
    nameAr: 'مجلس مدينة الخارجة',
    nameEn: 'Kharga City Council',
    description: 'مقر المجلس المحلي لمدينة الخارجة والخدمات الإدارية',
    category: 'government',
    address: 'ميدان المحطة، الخارجة',
    phone: '+20924921000',
    lat: 25.443,
    lon: 30.551,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/T4hZdDQElBc.jpg'],
  },
  {
    id: POI.POI08,
    nameAr: 'مجلس مدينة موط',
    nameEn: 'Mut City Council',
    description: 'مقر المجلس المحلي لمدينة موط والخدمات الإدارية في الداخلة',
    category: 'government',
    address: 'شارع السلام، موط، الداخلة',
    phone: '+20926820000',
    lat: 25.496,
    lon: 28.975,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/v4tLl97tXBY.jpg'],
  },
  {
    id: POI.POI09,
    nameAr: 'مجلس مدينة باريس',
    nameEn: 'Baris City Council',
    description: 'مقر المجلس المحلي لمدينة باريس والخدمات الإدارية',
    category: 'government',
    address: 'وسط مدينة باريس',
    lat: 24.656,
    lon: 30.594,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/wiki-baris-2.jpg'],
  },
  {
    id: POI.POI10,
    nameAr: 'مديرية التربية والتعليم',
    nameEn: 'Education Directorate',
    description: 'مقر مديرية التربية والتعليم بمحافظة الوادي الجديد',
    category: 'government',
    address: 'شارع المدارس، الخارجة',
    phone: '+20924922000',
    lat: 25.442,
    lon: 30.552,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/GNdp2Q4VZjw.jpg'],
  },
  {
    id: P11,
    nameAr: 'مدرسة الخارجة الثانوية بنين',
    nameEn: 'Kharga Secondary School for Boys',
    description: 'أكبر مدرسة ثانوية للبنين في مدينة الخارجة',
    category: 'service',
    address: 'شارع المدارس، الخارجة',
    lat: 25.445,
    lon: 30.553,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/DZOIE5bQGBg.jpg'],
  },
  {
    id: P12,
    nameAr: 'مدرسة الخارجة الثانوية بنات',
    nameEn: 'Kharga Secondary School for Girls',
    description: 'أكبر مدرسة ثانوية للبنات في مدينة الخارجة',
    category: 'service',
    address: 'شارع المدارس، الخارجة',
    lat: 25.446,
    lon: 30.554,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/3FRX4F_Kjak.jpg'],
  },
  {
    id: P13,
    nameAr: 'مدرسة موط الثانوية',
    nameEn: 'Mut Secondary School',
    description: 'المدرسة الثانوية الرئيسية في مدينة موط بواحة الداخلة',
    category: 'service',
    address: 'شارع التعليم، موط، الداخلة',
    lat: 25.493,
    lon: 28.976,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/1wZngiswH4M.jpg'],
  },
  {
    id: P14,
    nameAr: 'سوق الخارجة القديم',
    nameEn: 'Old Kharga Market',
    description:
      'السوق الشعبي التقليدي في قلب مدينة الخارجة، يضم محلات الحرف اليدوية والمنتجات المحلية',
    category: 'service',
    address: 'وسط مدينة الخارجة',
    lat: 25.437,
    lon: 30.548,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/wiki-al-qasr-1.jpg'],
  },
  {
    id: P15,
    nameAr: 'سوق موط المركزي',
    nameEn: 'Mut Central Market',
    description: 'السوق المركزي لمدينة موط يضم منتجات الواحة من تمور وزيت زيتون وحرف يدوية',
    category: 'service',
    address: 'شارع السوق، موط، الداخلة',
    lat: 25.495,
    lon: 28.979,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/wiki-al-qasr-2.jpg'],
  },
  {
    id: P16,
    nameAr: 'سوق الفرافرة',
    nameEn: 'Farafra Market',
    description: 'السوق الأسبوعي في الفرافرة لبيع المنتجات الزراعية المحلية',
    category: 'service',
    address: 'وسط مدينة الفرافرة',
    lat: 27.058,
    lon: 27.971,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/wiki-farafra-well.jpg'],
  },
  {
    id: P17,
    nameAr: 'مطار الخارجة',
    nameEn: 'Kharga Airport',
    description: 'مطار محافظة الوادي الجديد، يربط الخارجة بالقاهرة وعدد من المدن المصرية',
    category: 'service',
    address: 'طريق الخارجة - القاهرة',
    phone: '+20924923000',
    lat: 25.4535,
    lon: 30.5913,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/hp6Xj7LyZ1E.jpg'],
  },
  {
    id: P18,
    nameAr: 'مستشفى الفرافرة المركزي',
    nameEn: 'Farafra Central Hospital',
    description: 'المستشفى المركزي في مدينة الفرافرة يخدم سكان المدينة والزوار',
    category: 'service',
    address: 'شارع المستشفى، الفرافرة',
    phone: '+20927510456',
    lat: 27.055,
    lon: 27.968,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/wiki-white-desert-1.jpg'],
  },
  {
    id: P19,
    nameAr: 'نافورة مبروك',
    nameEn: 'Mabrouk Fountain',
    description: 'الميدان الرئيسي في مركز الخارجة، مكان للترفيه والتجمعات الاجتماعية',
    category: 'recreational',
    address: 'ميدان مبروك، وسط الخارجة',
    lat: 25.439,
    lon: 30.547,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/MB2eoqiNKiw.jpg'],
  },
  {
    id: P20,
    nameAr: 'مديرية الصحة بالوادي الجديد',
    nameEn: 'Health Directorate',
    description: 'مقر مديرية الصحة في محافظة الوادي الجديد، المسؤول عن الخدمات الصحية بالمحافظة',
    category: 'government',
    address: 'شارع الصحة، الخارجة',
    phone: '+20924924000',
    lat: 25.448,
    lon: 30.545,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/XaidrBZfEwU.jpg'],
  },
  {
    id: POI.POI11,
    nameAr: 'محطة ري بالطاقة الشمسية - مزرعة الأمل',
    nameEn: 'Solar Pump Station — Al-Amal Farm',
    description:
      'منظومة ضخ مياه تعمل بالطاقة الشمسية بقدرة 15 كيلوواط. تروي مزرعة الأمل للتمور والزيتون وتوفر ما يعادل 2000 لتر يومياً بدون كهرباء شبكة.',
    category: 'solar_installation',
    address: 'طريق الداخلة الصحراوي، كيلو 12',
    lat: 25.5231,
    lon: 28.9803,
    submittedBy: USER.FARMER_IBRAHIM,
    approvedBy: USER.ADMIN_SAYED,
    metadata: {
      capacity_kw: 15,
      monthly_kwh_savings: 450,
      install_year: 2023,
      system_type: 'pump',
    },
  },
  {
    id: POI.POI12,
    nameAr: 'منزل أسرة محمد - نظام شمسي سكني',
    nameEn: 'Mohamed Family Home — Rooftop Solar',
    description:
      'نظام شمسي سكني على سطح المنزل بقدرة 5 كيلوواط مع بطارية تخزين. يغطي 80٪ من احتياجات الكهرباء المنزلية ويوفر نحو 600 جنيه شهرياً.',
    category: 'solar_installation',
    address: 'حي الزهور، الخارجة',
    lat: 25.4427,
    lon: 30.5521,
    submittedBy: USER.RESIDENT_MOHAMED,
    approvedBy: USER.ADMIN_SAYED,
    metadata: {
      capacity_kw: 5,
      monthly_kwh_savings: 150,
      install_year: 2024,
      system_type: 'rooftop',
    },
  },
  {
    id: POI.POI13,
    nameAr: 'مدرسة الفرافرة الابتدائية - نظام شمسي',
    nameEn: 'Farafra Primary School — Solar System',
    description:
      'نظام طاقة شمسية على سطح مدرسة الفرافرة الابتدائية بقدرة 10 كيلوواط. موّلت جزئياً بمنحة صندوق الطاقة المتجددة ويخدم 320 طالباً.',
    category: 'solar_installation',
    address: 'شارع المدارس، قصر الفرافرة',
    lat: 27.0589,
    lon: 27.9684,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    metadata: {
      capacity_kw: 10,
      monthly_kwh_savings: 300,
      install_year: 2022,
      system_type: 'rooftop',
    },
  },
  {
    id: POI.POI14,
    nameAr: 'محطة تحلية المياه الشمسية - باريس',
    nameEn: 'Solar Water Desalination Station — Baris',
    description:
      'محطة تحلية مياه جوفية تعمل بالطاقة الشمسية بقدرة 20 كيلوواط. تنتج 5000 لتر يومياً من المياه الصالحة للشرب لخدمة 300 أسرة في منطقة باريس الجنوبية.',
    category: 'solar_installation',
    address: 'طريق باريس الجنوبية، جنوب الخارجة',
    lat: 24.663,
    lon: 30.597,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/solar-farm-1.jpg'],
    metadata: {
      capacity_kw: 20,
      monthly_kwh_savings: 600,
      install_year: 2023,
      system_type: 'desalination',
    },
  },
  {
    id: POI.POI15,
    nameAr: 'مزرعة الخارجة الشمسية - الطاقة الزراعية',
    nameEn: 'Kharga Solar Farm — Agricultural Energy',
    description:
      'مزرعة شمسية بقدرة 50 كيلوواط تمد مضخات الري وورش التبريد بطاقة نظيفة. موّلت بمنحة الصندوق الاجتماعي للتنمية وتخدم 12 مزرعة مجاورة.',
    category: 'solar_installation',
    address: 'المنطقة الزراعية الشمالية، الخارجة',
    lat: 25.563,
    lon: 30.558,
    submittedBy: USER.FARMER_IBRAHIM,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/solar-panel-1.jpg'],
    metadata: {
      capacity_kw: 50,
      monthly_kwh_savings: 1500,
      install_year: 2024,
      system_type: 'ground_mount',
    },
  },
  {
    id: POI.POI16,
    nameAr: 'منظومة إضاءة شوارع الداخلة الشمسية',
    nameEn: 'Dakhla Solar Street Lighting Network',
    description:
      'شبكة إضاءة شوارع تعمل بالطاقة الشمسية تضم 80 عمود إنارة ذكي في مدينة قصر الداخلة. تعمل دون اتصال بالشبكة الكهربائية وتوفر 40000 جنيه سنوياً في فواتير الكهرباء.',
    category: 'solar_installation',
    address: 'شارع الجمهورية وشارع المدارس، موط، الداخلة',
    lat: 25.689,
    lon: 28.885,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/solar-village-1.jpg'],
    metadata: {
      capacity_kw: 8,
      monthly_kwh_savings: 240,
      install_year: 2023,
      system_type: 'street_lighting',
    },
  },
  {
    id: POI.POI17,
    nameAr: 'مركز صحي الفرافرة - طاقة شمسية مستقلة',
    nameEn: 'Farafra Health Centre — Off-Grid Solar',
    description:
      'نظام شمسي مستقل عن الشبكة بقدرة 8 كيلوواط مع بنك بطاريات يكفي 12 ساعة. يضمن تشغيل الثلاجات الطبية وأجهزة العيادة على مدار الساعة في منطقة بعيدة عن الشبكة.',
    category: 'solar_installation',
    address: 'شارع الصحة، قصر الفرافرة',
    lat: 27.062,
    lon: 27.974,
    submittedBy: USER.ADMIN_SAYED,
    approvedBy: USER.ADMIN_SAYED,
    images: ['/images/seed/solar-rooftop-1.jpg'],
    metadata: {
      capacity_kw: 8,
      monthly_kwh_savings: 240,
      install_year: 2021,
      system_type: 'off_grid',
    },
  },
];
