import { LISTING, USER } from '../../../../../scripts/seed/shared-ids.js';

/** Listing seed record (location is set via raw SQL at insert time) */
export interface SeedListing {
  id: string;
  ownerId: string;
  listingType: 'real_estate' | 'land' | 'business';
  transaction: 'sale' | 'rent';
  titleAr: string;
  titleEn: string;
  description: string;
  category:
    | 'place'
    | 'accommodation'
    | 'restaurant'
    | 'service'
    | 'activity'
    | 'transport'
    | 'education'
    | 'healthcare'
    | 'shopping';
  price: number;
  district: string;
  address: string;
  slug: string;
  status: 'active';
  isVerified: boolean;
  isPublished: boolean;
  lat: number;
  lon: number;
}

/** Essential layer: 3 listings (one per type) */
export const essentialListings: SeedListing[] = [
  {
    id: LISTING.L01,
    ownerId: USER.RESIDENT_MOHAMED,
    listingType: 'real_estate',
    transaction: 'rent',
    titleAr: 'شقة مفروشة للإيجار في الخارجة',
    titleEn: 'Furnished Apartment for Rent in Kharga',
    description:
      'شقة مفروشة بالكامل في قلب مدينة الخارجة. تتكون من غرفتين وصالة ومطبخ وحمام. قريبة من الخدمات والمحلات التجارية.',
    category: 'accommodation',
    price: 350000,
    district: 'kharga',
    address: 'شارع جمال عبد الناصر، الخارجة',
    slug: 'shaqqa-mafrousha-kharga',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.4363,
    lon: 30.555,
  },
  {
    id: LISTING.L02,
    ownerId: USER.INVESTOR_MAHMOUD,
    listingType: 'land',
    transaction: 'sale',
    titleAr: 'مزرعة تمور 50 فدان بالداخلة',
    titleEn: 'Date Palm Farm 50 Acres in Dakhla',
    description:
      'مزرعة تمور منتجة بمساحة 50 فداناً في واحة الداخلة. المزرعة مزروعة بأشجار نخيل البلح المثمرة ولها حصة مياه من بئر ارتوازية. مناسبة للاستثمار الزراعي.',
    category: 'place',
    price: 500000000,
    district: 'dakhla',
    address: 'طريق موط الزراعي، الداخلة',
    slug: 'mazraat-tumur-dakhla',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.5,
    lon: 28.98,
  },
  {
    id: LISTING.L03,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'محل تجاري بسوق الخارجة المركزي',
    titleEn: 'Commercial Shop in Kharga Central Market',
    description:
      'محل تجاري في موقع مميز بسوق الخارجة المركزي. مساحة 40 متراً مربعاً مناسبة لأي نشاط تجاري. الإيجار شامل الرسوم.',
    category: 'service',
    price: 150000,
    district: 'kharga',
    address: 'سوق الخارجة المركزي، وسط المدينة',
    slug: 'mahal-tujari-souq-kharga',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.438,
    lon: 30.553,
  },
];

// Extra IDs for showcase listings (L11-L40) — not cross-service refs so defined here.
// L11-L16 are exported because reviews.ts references them.
export const L11 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567811';
export const L12 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567812';
export const L13 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567813';
export const L14 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567814';
export const L15 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567815';
export const L16 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567816';
const L17 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567817';
const L18 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567818';
const L19 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567819';
const L20 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567820';
const L21 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567821';
const L22 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567822';
const L23 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567823';
const L24 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567824';
const L25 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567825';
const L26 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567826';
const L27 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567827';
const L28 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567828';
const L29 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567829';
const L30 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567830';
const L31 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567831';
const L32 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567832';
const L33 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567833';
const L34 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567834';
const L35 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567835';
const L36 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567836';
const L37 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567837';
const L38 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567838';
const L39 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567839';
const L40 = 'a1b2c3d4-e5f6-7890-abcd-ef1234567840';

/** Showcase layer: additional listings */
export const showcaseListings: SeedListing[] = [
  // ── Accommodation (11 more → 12 total) ──────────────────────────────
  {
    id: LISTING.L04,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'real_estate',
    transaction: 'rent',
    titleAr: 'فندق قصر البجوات',
    titleEn: 'Bagawat Palace Hotel',
    description:
      'فندق سياحي فريد يقع بجوار جبانة البجوات الأثرية. يضم 30 غرفة مكيفة بإطلالات صحراوية رائعة، ومسبح خارجي وحديقة استوائية.',
    category: 'accommodation',
    price: 80000,
    district: 'kharga',
    address: 'طريق جبانة البجوات، شمال الخارجة',
    slug: 'funduq-qasr-bagawat',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.458,
    lon: 30.544,
  },
  {
    id: LISTING.L05,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'real_estate',
    transaction: 'rent',
    titleAr: 'لودج الطرفة الصحراوية',
    titleEn: 'Al-Tarfa Desert Lodge',
    description:
      'منتجع فاخر وسط الصحراء يحاكي التصميم المعماري المحلي. كل غرفة مزودة بحمام خاص وتراس مطل على واحة الداخلة. يشمل مطعماً يقدم المأكولات المحلية.',
    category: 'accommodation',
    price: 120000,
    district: 'dakhla',
    address: 'طريق موط الصحراوي، 10 كم غرب موط',
    slug: 'lodge-altarfa-sahrawi',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.67,
    lon: 28.95,
  },
  {
    id: L11,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'real_estate',
    transaction: 'rent',
    titleAr: 'شاليه صحراوي بالفرافرة',
    titleEn: 'Desert Chalet in Farafra',
    description:
      'شاليه هادئ بتصميم طيني تقليدي في قلب واحة الفرافرة. مكون من غرفة نوم وصالة ومطبخ صغير. مناسب للأزواج والعائلات الراغبة في تجربة حياة الواحات.',
    category: 'accommodation',
    price: 60000,
    district: 'farafra',
    address: 'وسط مدينة الفرافرة، بالقرب من البئر الرومانية',
    slug: 'shalet-sahrawi-farafra',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 27.0567,
    lon: 27.9703,
  },
  {
    id: L12,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'real_estate',
    transaction: 'rent',
    titleAr: 'استراحة واحة الداخلة',
    titleEn: 'Dakhla Oasis Rest House',
    description:
      'استراحة بسيطة وأنيقة في موط عاصمة الداخلة. تحتوي على 8 غرف مع مياه ساخنة ومكيفات ومطعم يقدم الوجبات المنزلية. سعر مناسب للزوار والمسافرين.',
    category: 'accommodation',
    price: 45000,
    district: 'dakhla',
    address: 'شارع المطار، موط، الداخلة',
    slug: 'istirahat-wahat-dakhla',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.4946,
    lon: 28.9781,
  },
  {
    id: L13,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'real_estate',
    transaction: 'rent',
    titleAr: 'فندق الخارجة السياحي',
    titleEn: 'Kharga Tourism Hotel',
    description:
      'فندق من فئة ثلاث نجوم في وسط مدينة الخارجة. يضم 45 غرفة ومطعماً وقاعة اجتماعات ومواقف سيارات مجانية. موقع مركزي قريب من المتاحف والمعابد.',
    category: 'accommodation',
    price: 70000,
    district: 'kharga',
    address: 'شارع التحرير، وسط مدينة الخارجة',
    slug: 'funduq-kharga-siyahi',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.44,
    lon: 30.55,
  },
  {
    id: L14,
    ownerId: USER.RESIDENT_MOHAMED,
    listingType: 'real_estate',
    transaction: 'rent',
    titleAr: 'شقق مفروشة للإيجار بالداخلة',
    titleEn: 'Furnished Apartments for Rent in Dakhla',
    description:
      'مجمع شقق مفروشة بالكامل في موط. خمس شقق متاحة بإيجار شهري. كل شقة تشمل غرفتين ومطبخاً وحمامين. الإيجار شامل الكهرباء والمياه.',
    category: 'accommodation',
    price: 200000,
    district: 'dakhla',
    address: 'شارع المستشفى، موط، الداخلة',
    slug: 'shiqaq-mafrusha-dakhla',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.5,
    lon: 28.96,
  },
  {
    id: L15,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'real_estate',
    transaction: 'rent',
    titleAr: 'استراحة باريس التراثية',
    titleEn: 'Baris Heritage Rest House',
    description:
      'استراحة تراثية مبنية بالطوب اللبن في مدينة باريس. تضم 6 غرف ذات طابع معماري نوبي أصيل. مناسبة للسياحة الثقافية وزيارة معبد دوش القريب.',
    category: 'accommodation',
    price: 40000,
    district: 'baris',
    address: 'وسط مدينة باريس، بالقرب من معبد دوش',
    slug: 'istirahat-baris-turathiyya',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 24.6544,
    lon: 30.5956,
  },
  {
    id: L16,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'real_estate',
    transaction: 'rent',
    titleAr: 'مخيم سياحي بالصحراء البيضاء',
    titleEn: 'Eco Camp in White Desert',
    description:
      'مخيم سياحي فاخر (غلامبينغ) في الصحراء البيضاء. خيام مجهزة بسرائر مريحة وإضاءة وأجهزة تدفئة. يشمل السعر العشاء والإفطار والجولة الليلية تحت النجوم.',
    category: 'accommodation',
    price: 150000,
    district: 'farafra',
    address: 'الصحراء البيضاء، 45 كم شمال الفرافرة',
    slug: 'mukhayyam-sahraa-bayda',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 27.25,
    lon: 28.05,
  },
  {
    id: L17,
    ownerId: USER.RESIDENT_MOHAMED,
    listingType: 'real_estate',
    transaction: 'rent',
    titleAr: 'بيت ضيافة في بلاط القديمة',
    titleEn: 'Guesthouse in Old Balat',
    description:
      'بيت ضيافة أثري داخل مدينة بلاط التاريخية. الغرف بتصميم قديم أصيل بأسقف خشبية ونوافذ صغيرة. تجربة فريدة للعيش في قرية تاريخية تعود لألف عام.',
    category: 'accommodation',
    price: 30000,
    district: 'balat',
    address: 'مدينة بلاط القديمة، الداخلة',
    slug: 'bayt-diyafa-balat',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.5667,
    lon: 29.2667,
  },
  {
    id: L18,
    ownerId: USER.INVESTOR_MAHMOUD,
    listingType: 'real_estate',
    transaction: 'sale',
    titleAr: 'شقة فاخرة للبيع بالخارجة',
    titleEn: 'Luxury Apartment for Sale in Kharga',
    description:
      'شقة فاخرة بمساحة 180 متراً مربعاً في مجمع سكني حديث بالخارجة. تشمل 3 غرف نوم، 2 حمام، صالة كبيرة ومطبخ أمريكي. التشطيب سوبر لوكس وبها جراج خاص.',
    category: 'accommodation',
    price: 180000000,
    district: 'kharga',
    address: 'حي المساكن الجديد، الخارجة',
    slug: 'shaqqa-fakira-kharga-sale',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.4363,
    lon: 30.555,
  },
  {
    id: L19,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'real_estate',
    transaction: 'rent',
    titleAr: 'فيلا واحة للإيجار بالداخلة',
    titleEn: 'Oasis Villa for Rent in Dakhla',
    description:
      'فيلا خاصة محاطة ببستان نخيل في واحة الداخلة. تتكون من 4 غرف نوم وصالتين ومطبخ كبير وحديقة خاصة. مناسبة للعائلات الكبيرة والإقامة الطويلة.',
    category: 'accommodation',
    price: 500000,
    district: 'dakhla',
    address: 'منطقة العيون الساخنة، الداخلة',
    slug: 'villa-wahat-rent-dakhla',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.52,
    lon: 28.95,
  },

  // ── Real Estate / Land (9 more → 10 total) ──────────────────────────
  {
    id: LISTING.L09,
    ownerId: USER.INVESTOR_MAHMOUD,
    listingType: 'land',
    transaction: 'sale',
    titleAr: 'أرض زراعية 10 أفدنة بالفرافرة',
    titleEn: 'Agricultural Land 10 Acres in Farafra',
    description:
      'أرض زراعية خصبة بمساحة 10 أفدنة في واحة الفرافرة. مزودة بحصة مياه من مشروع الاستصلاح الزراعي. مناسبة لزراعة الزيتون والتمور والخضروات.',
    category: 'place',
    price: 80000000,
    district: 'farafra',
    address: 'مشروع استصلاح الأراضي، الفرافرة',
    slug: 'ard-zariya-farafra',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 27.06,
    lon: 27.96,
  },
  {
    id: LISTING.L10,
    ownerId: USER.RESIDENT_MOHAMED,
    listingType: 'real_estate',
    transaction: 'rent',
    titleAr: 'شقة طلابية بالقرب من جامعة الوادي الجديد',
    titleEn: 'Student Apartment near New Valley University',
    description:
      'شقة مناسبة للطلاب بالقرب من جامعة الوادي الجديد. غرفتان، مطبخ وحمام. الإيجار شامل الكهرباء. على بعد 10 دقائق مشياً من الجامعة.',
    category: 'accommodation',
    price: 150000,
    district: 'kharga',
    address: 'شارع الجامعة، الخارجة',
    slug: 'shaqqa-tulabiyya-jamia',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.45,
    lon: 30.56,
  },
  {
    id: L20,
    ownerId: USER.INVESTOR_MAHMOUD,
    listingType: 'land',
    transaction: 'sale',
    titleAr: 'قطعة أرض سكنية بالخارجة',
    titleEn: 'Residential Plot in Kharga',
    description:
      'قطعة أرض سكنية بمساحة 500 متر مربع في حي المساكن الجديد بالخارجة. الأرض مرافقها مكتملة (كهرباء، مياه، صرف صحي). مستندات نظيفة وجاهزة للبناء.',
    category: 'place',
    price: 50000000,
    district: 'kharga',
    address: 'حي المساكن الجديد، الخارجة',
    slug: 'qitat-ard-sukniyya-kharga',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.4363,
    lon: 30.555,
  },
  {
    id: L21,
    ownerId: USER.INVESTOR_MAHMOUD,
    listingType: 'land',
    transaction: 'sale',
    titleAr: 'مزرعة زيتون بالفرافرة',
    titleEn: 'Olive Farm in Farafra',
    description:
      'مزرعة زيتون منتجة بمساحة 30 فداناً في الفرافرة. تضم أكثر من 2000 شجرة زيتون مثمرة. لها حصة مياه من بئر ارتوازية خاصة. إنتاجها السنوي 15 طناً من الزيتون.',
    category: 'place',
    price: 120000000,
    district: 'farafra',
    address: 'طريق الفرافرة الزراعي، 5 كم جنوب المدينة',
    slug: 'mazraat-zaytun-farafra',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 27.04,
    lon: 27.96,
  },
  {
    id: L22,
    ownerId: USER.INVESTOR_MAHMOUD,
    listingType: 'real_estate',
    transaction: 'sale',
    titleAr: 'شقة للبيع بالخارجة - 3 غرف',
    titleEn: '3-Bedroom Apartment for Sale in Kharga',
    description:
      'شقة 3 غرف في دور أول بعمارة حديثة في وسط الخارجة. التشطيب عادي وجاهزة للسكن. بها مساحة تخزين إضافية وإمكانية تقسيم طابق للمحل التجاري.',
    category: 'accommodation',
    price: 120000000,
    district: 'kharga',
    address: 'شارع 23 يوليو، وسط الخارجة',
    slug: 'shaqqa-lialbay-kharga-3ghorf',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.44,
    lon: 30.551,
  },
  {
    id: L23,
    ownerId: USER.INVESTOR_MAHMOUD,
    listingType: 'land',
    transaction: 'sale',
    titleAr: 'أرض صناعية بالداخلة',
    titleEn: 'Industrial Land in Dakhla',
    description:
      'قطعة أرض صناعية بمساحة 2000 متر مربع في المنطقة الصناعية بالداخلة. قريبة من الطريق الصحراوي الرئيسي. مناسبة لإقامة مصنع أو مستودعات أو ورش عمل.',
    category: 'place',
    price: 200000000,
    district: 'dakhla',
    address: 'المنطقة الصناعية، موط، الداخلة',
    slug: 'ard-sinaiiya-dakhla',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.48,
    lon: 28.97,
  },
  {
    id: L24,
    ownerId: USER.RESIDENT_MOHAMED,
    listingType: 'real_estate',
    transaction: 'sale',
    titleAr: 'منزل عائلي للبيع في بلاط',
    titleEn: 'Family Home for Sale in Balat',
    description:
      'منزل عائلي من طابقين في قرية بلاط. الدور الأرضي يشمل صالة ومطبخاً وحمامين. الدور العلوي يشمل 4 غرف نوم. بحديقة صغيرة وتراس مطل على النخيل.',
    category: 'accommodation',
    price: 80000000,
    district: 'balat',
    address: 'شارع القرية الرئيسي، بلاط، الداخلة',
    slug: 'manzil-lialbay-balat',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.5667,
    lon: 29.2667,
  },
  {
    id: L25,
    ownerId: USER.RESIDENT_MOHAMED,
    listingType: 'real_estate',
    transaction: 'rent',
    titleAr: 'شقة للإيجار بالداخلة - موقع مميز',
    titleEn: 'Apartment for Rent in Dakhla',
    description:
      'شقة نظيفة بغرفتين في موقع مميز في موط. الإيجار شامل الخدمات. قريبة من الأسواق والمستشفيات. الشقة في الدور الثالث مع مصعد.',
    category: 'accommodation',
    price: 250000,
    district: 'dakhla',
    address: 'شارع النيل، موط، الداخلة',
    slug: 'shaqqa-lilijjar-dakhla',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.4946,
    lon: 28.9781,
  },
  {
    id: L26,
    ownerId: USER.INVESTOR_MAHMOUD,
    listingType: 'land',
    transaction: 'sale',
    titleAr: 'أرض زراعية بباريس - 20 فدان',
    titleEn: 'Agricultural Land in Baris - 20 Acres',
    description:
      'أرض زراعية خصبة بمساحة 20 فداناً في مشروع استصلاح باريس. تصلح لزراعة التمور والخضروات والقمح. بها حصة مياه مضمونة من المشروع الزراعي القومي.',
    category: 'place',
    price: 60000000,
    district: 'baris',
    address: 'مشروع استصلاح الأراضي، باريس',
    slug: 'ard-zariya-baris-20feddan',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 24.6,
    lon: 30.6,
  },

  // ── Restaurants & Cafes (7 more → 8 total) ──────────────────────────
  {
    id: LISTING.L06,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'مطعم الواحة - الخارجة',
    titleEn: 'Al-Waha Restaurant - Kharga',
    description:
      'مطعم شعبي يقدم المأكولات المحلية الأصيلة في قلب الخارجة. متخصص في الكباب والمشويات والأطباق الصعيدية التقليدية. يستوعب 80 شخصاً. ',
    category: 'restaurant',
    price: 300000,
    district: 'kharga',
    address: 'شارع التحرير، وسط مدينة الخارجة',
    slug: 'mataem-alwaha-kharga',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.4363,
    lon: 30.555,
  },
  {
    id: L27,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'مقهى البجوات السياحي',
    titleEn: 'Bagawat Tourism Cafe',
    description:
      'مقهى سياحي بإطلالة على جبانة البجوات الأثرية. يقدم المشروبات الساخنة والعصائر الطازجة والوجبات الخفيفة. جلسة خارجية مريحة تحت ظل النخيل.',
    category: 'restaurant',
    price: 200000,
    district: 'kharga',
    address: 'طريق معبد هيبس، شمال الخارجة',
    slug: 'maqha-bagawat-siyahi',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.456,
    lon: 30.545,
  },
  {
    id: L28,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'مطعم نخلة الداخلة',
    titleEn: 'Nakhlat Al-Dakhla Restaurant',
    description:
      'مطعم عائلي في موط يتخصص في الأطباق المحلية الداخلاوية. يشتهر بطبق كنافة الدفن بالرمال وشوربة العدس بالكمون. يستوعب 60 شخصاً مع جلسة حديقة.',
    category: 'restaurant',
    price: 250000,
    district: 'dakhla',
    address: 'شارع الكورنيش، موط، الداخلة',
    slug: 'mataem-nakhla-dakhla',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.4946,
    lon: 28.9781,
  },
  {
    id: L29,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'كافيه الصحراء البيضاء',
    titleEn: 'White Desert Cafe',
    description:
      'مقهى بيئي في الفرافرة يقدم خيارات نباتية وعضوية. مبني من مواد طبيعية وبه إطلالة على السهل الصحراوي. يقدم القهوة العربية والشاي بالأعشاب الصحراوية.',
    category: 'restaurant',
    price: 120000,
    district: 'farafra',
    address: 'المدخل الشمالي لمدينة الفرافرة',
    slug: 'cafe-sahraa-bayda-farafra',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 27.06,
    lon: 27.972,
  },
  {
    id: L30,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'مطعم بلاط التراثي',
    titleEn: 'Balat Heritage Restaurant',
    description:
      'مطعم داخل مدينة بلاط التاريخية. يقدم وجبات تقليدية مطبوخة في أفران الطين والفحم. يوفر تجربة طعام أصيلة في أجواء الحارات التاريخية.',
    category: 'restaurant',
    price: 100000,
    district: 'balat',
    address: 'حارة الشيخ، بلاط القديمة، الداخلة',
    slug: 'mataem-balat-turathi',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.5667,
    lon: 29.2667,
  },
  {
    id: L31,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'مطعم باريس الشعبي',
    titleEn: 'Baris Popular Restaurant',
    description:
      'مطعم شعبي محلي في مدينة باريس يقدم الغداء والعشاء طوال اليوم. يشتهر بالكشري والمحشي والفراخ المشوية. أسعار مناسبة ومقبلات مجانية.',
    category: 'restaurant',
    price: 80000,
    district: 'baris',
    address: 'شارع السوق الرئيسي، باريس',
    slug: 'mataem-baris-shaabi',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 24.6544,
    lon: 30.5956,
  },
  {
    id: L32,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'مقهى واحة الراحة - الداخلة',
    titleEn: 'Oasis Rest Cafe - Dakhla',
    description:
      'مقهى عصري في قلب موط. يقدم المشروبات الساخنة والباردة والحلويات المتنوعة. مجهز بشبكة إنترنت سريعة ومكيف. يفتح من الصباح حتى منتصف الليل.',
    category: 'restaurant',
    price: 120000,
    district: 'dakhla',
    address: 'شارع التحرير، موط، الداخلة',
    slug: 'maqha-wahat-raha-dakhla',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.5,
    lon: 28.98,
  },
  {
    id: L33,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'مطعم فول وطعمية الخارجة',
    titleEn: 'Ful and Falafel Restaurant - Kharga',
    description:
      'مطعم شعبي للإفطار والعشاء يقدم الفول والطعمية والبيض والجبن. معروف بين السكان المحليين بجودة طعامه الأصيل وأسعاره الشعبية المناسبة.',
    category: 'restaurant',
    price: 60000,
    district: 'kharga',
    address: 'شارع الجمهورية، الخارجة',
    slug: 'mataem-foul-kharga',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.435,
    lon: 30.552,
  },

  // ── Services (3 more → 5 total) ──────────────────────────────────────
  {
    id: LISTING.L07,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'صيدلية الوادي - الخارجة',
    titleEn: 'Al-Wadi Pharmacy - Kharga',
    description:
      'صيدلية مجهزة في وسط الخارجة تعمل 24 ساعة. تحتوي على قسم للأدوية والمستلزمات الطبية وقسم للمستحضرات التجميلية. يوجد صيدلاني مقيم طوال اليوم.',
    category: 'service',
    price: 180000,
    district: 'kharga',
    address: 'شارع المستشفى، الخارجة',
    slug: 'saidaliyat-alwadi-kharga',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.438,
    lon: 30.553,
  },
  {
    id: L34,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'ورشة سيارات وإطارات بالخارجة',
    titleEn: 'Auto Repair and Tires Workshop - Kharga',
    description:
      'ورشة متكاملة لصيانة السيارات وتغيير الإطارات في الخارجة. مجهزة بأحدث معدات الفحص والإصلاح. تستقبل جميع أنواع السيارات وتوفر قطع غيار أصلية.',
    category: 'service',
    price: 200000,
    district: 'kharga',
    address: 'طريق الكيلو 6، الخارجة',
    slug: 'warshat-sayyarat-kharga',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.432,
    lon: 30.548,
  },
  {
    id: L35,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'سوبر ماركت واحة التسوق - الداخلة',
    titleEn: 'Oasis Shopping Supermarket - Dakhla',
    description:
      'سوبر ماركت متكامل في موط يحتوي على أكثر من 3000 صنف من المواد الغذائية والمنزلية. يستقبل الزبائن من 8 صباحاً حتى 12 ليلاً. يوفر خدمة التوصيل للمنازل.',
    category: 'service',
    price: 120000,
    district: 'dakhla',
    address: 'شارع السوق المركزي، موط، الداخلة',
    slug: 'supermarket-wahat-dakhla',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.4946,
    lon: 28.9781,
  },
  {
    id: L36,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'مكتبة ومطبعة الوادي الجديد',
    titleEn: 'New Valley Bookstore and Printing',
    description:
      'مكتبة شاملة وخدمات طباعة في وسط الخارجة. تبيع الكتب المدرسية والقرطاسية ولوازم الطلاب. قسم الطباعة يوفر خدمات التصوير والطباعة الملونة والتجليد.',
    category: 'service',
    price: 100000,
    district: 'kharga',
    address: 'شارع الجامعة، الخارجة',
    slug: 'maktaba-matbaa-alwadi',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.435,
    lon: 30.552,
  },

  // ── Activities (4 more → 5 total) ────────────────────────────────────
  {
    id: LISTING.L08,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'شركة سفاري الصحراء - الفرافرة',
    titleEn: 'Desert Safari Company - Farafra',
    description:
      'شركة سياحية متخصصة في رحلات السفاري الصحراوي في الصحراء البيضاء والسوداء. تملك أسطولاً من سيارات الجيب وتوفر مرشدين محليين خبراء بكل مسارات الصحراء.',
    category: 'activity',
    price: 250000,
    district: 'farafra',
    address: 'وسط مدينة الفرافرة، بجوار المتحف المحلي',
    slug: 'sharikat-safari-sahraa-farafra',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 27.0567,
    lon: 27.9703,
  },
  {
    id: L37,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'تأجير دراجات رباعية ATV بالفرافرة',
    titleEn: 'ATV Quad Bike Rental in Farafra',
    description:
      'خدمة تأجير دراجات رباعية للتجول في رمال الصحراء البيضاء. يشمل الاستئجار خوذة وسترة واقية وتعليمات الأمان. يتوفر مرشد اختياري لمصاحبة المجموعات.',
    category: 'activity',
    price: 100000,
    district: 'farafra',
    address: 'مدخل الصحراء البيضاء، الفرافرة',
    slug: 'ajiret-darrajat-atv-farafra',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 27.06,
    lon: 27.96,
  },
  {
    id: L38,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'مركز ركوب الخيل - الداخلة',
    titleEn: 'Horse Riding Center - Dakhla',
    description:
      'مركز ترفيهي لركوب الخيل في واحة الداخلة. يوفر الخيول للمبتدئين والمحترفين مع إشراف مدربين متخصصين. تشمل الجلسة جولة حول مزارع النخيل وعيون المياه.',
    category: 'activity',
    price: 150000,
    district: 'dakhla',
    address: 'منطقة العيون الساخنة، الداخلة',
    slug: 'markaz-rukub-khayl-dakhla',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.52,
    lon: 28.95,
  },
  {
    id: L39,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'رحلات طائرات شراعية فوق الصحراء',
    titleEn: 'Paragliding Tours over the Desert',
    description:
      'رحلات طيران شراعي فوق الصحراء البيضاء والمزارع الخضراء. يتوفر مدربون معتمدون دولياً. تناسب المبتدئين والمحترفين. أفضل تجربة لاستشعار جمال الواحة من السماء.',
    category: 'activity',
    price: 200000,
    district: 'farafra',
    address: 'سهل الفرافرة المفتوح، شرق المدينة',
    slug: 'rihlat-tayaran-shiraiyi-farafra',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 27.07,
    lon: 28.0,
  },
  {
    id: L40,
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'مركز العلاج بالمياه الساخنة - الداخلة',
    titleEn: 'Hot Springs Therapy Center - Dakhla',
    description:
      'مركز علاجي يستخدم المياه المعدنية الساخنة الطبيعية في الداخلة. يقدم جلسات علاجية للمفاصل والروماتيزم وأمراض الجلد. متاح للأفراد والعائلات بجدول مواعيد مرن.',
    category: 'activity',
    price: 180000,
    district: 'dakhla',
    address: 'عيون موط، الداخلة',
    slug: 'markaz-miah-sakhina-dakhla',
    status: 'active',
    isVerified: true,
    isPublished: true,
    lat: 25.5,
    lon: 28.98,
  },

  // ── Pending verification (admin moderation demo) ─────────────────────
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567841',
    ownerId: USER.RESIDENT_MOHAMED,
    listingType: 'real_estate',
    transaction: 'rent',
    titleAr: 'استراحة صحراوية للإيجار - الفرافرة',
    titleEn: 'Desert Rest House for Rent - Farafra',
    description:
      'استراحة صغيرة بالقرب من الصحراء البيضاء تتكون من غرفتين وحمام وتراس مفتوح. مناسبة للمسافرين والسياح الراغبين في تجربة المبيت الصحراوي.',
    category: 'accommodation',
    price: 60000,
    district: 'farafra',
    address: 'طريق الصحراء البيضاء، الفرافرة',
    slug: 'istiraha-sahrawi-farafra-pending',
    status: 'active',
    isVerified: false,
    isPublished: false,
    lat: 27.07,
    lon: 27.98,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567842',
    ownerId: USER.MERCHANT_KHALED,
    listingType: 'business',
    transaction: 'rent',
    titleAr: 'محل بيع منتجات الواحة - الداخلة',
    titleEn: 'Oasis Products Shop - Dakhla',
    description:
      'محل متخصص في بيع منتجات الواحة المحلية من تمور وزيت زيتون وعسل طبيعي وصابون أعشاب. يستهدف السياح والمشترين بالجملة والتجزئة.',
    category: 'shopping',
    price: 90000,
    district: 'dakhla',
    address: 'شارع السوق، موط، الداخلة',
    slug: 'mahal-muntajat-wahaat-dakhla-pending',
    status: 'active',
    isVerified: false,
    isPublished: false,
    lat: 25.495,
    lon: 28.975,
  },
];
