ALTER TABLE "guide_booking"."attractions" ALTER COLUMN "search_vector" SET DATA TYPE tsvector;--> statement-breakpoint
ALTER TABLE "guide_booking"."attractions" drop column "search_vector";--> statement-breakpoint
ALTER TABLE "guide_booking"."attractions" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('simple', guide_booking.normalize_arabic(coalesce("guide_booking"."attractions"."name_ar", ''))), 'A') || setweight(to_tsvector('simple', coalesce("guide_booking"."attractions"."name_en", '')), 'A') || setweight(to_tsvector('simple', guide_booking.normalize_arabic(coalesce("guide_booking"."attractions"."description_ar", ''))), 'B') || setweight(to_tsvector('simple', coalesce("guide_booking"."attractions"."description_en", '')), 'B') || setweight(to_tsvector('simple', guide_booking.normalize_arabic(coalesce("guide_booking"."attractions"."history_ar", ''))), 'B')) STORED;--> statement-breakpoint
ALTER TABLE "guide_booking"."guides" ALTER COLUMN "search_vector" SET DATA TYPE tsvector;--> statement-breakpoint
ALTER TABLE "guide_booking"."guides" drop column "search_vector";--> statement-breakpoint
ALTER TABLE "guide_booking"."guides" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('simple', guide_booking.normalize_arabic(coalesce("guide_booking"."guides"."bio_ar", ''))), 'A') || setweight(to_tsvector('simple', coalesce("guide_booking"."guides"."bio_en", '')), 'A')) STORED;--> statement-breakpoint
ALTER TABLE "guide_booking"."tour_packages" ALTER COLUMN "search_vector" SET DATA TYPE tsvector;--> statement-breakpoint
ALTER TABLE "guide_booking"."tour_packages" drop column "search_vector";--> statement-breakpoint
ALTER TABLE "guide_booking"."tour_packages" ADD COLUMN "search_vector" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector('simple', guide_booking.normalize_arabic(coalesce("guide_booking"."tour_packages"."title_ar", ''))), 'A') || setweight(to_tsvector('simple', coalesce("guide_booking"."tour_packages"."title_en", '')), 'A') || setweight(to_tsvector('simple', guide_booking.normalize_arabic(coalesce("guide_booking"."tour_packages"."description", ''))), 'B')) STORED;--> statement-breakpoint
CREATE INDEX "idx_attractions_search" ON "guide_booking"."attractions" USING gin ("search_vector");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_bookings_active_slot" ON "guide_booking"."bookings" USING btree ("guide_id","booking_date","start_time") WHERE "guide_booking"."bookings"."status" IN ('pending', 'confirmed', 'in_progress');--> statement-breakpoint
CREATE INDEX "idx_guides_search" ON "guide_booking"."guides" USING gin ("search_vector");--> statement-breakpoint
CREATE INDEX "idx_tour_packages_search" ON "guide_booking"."tour_packages" USING gin ("search_vector");